# https://vuepress.github.io/zh/guide/deployment.html#github-pages
name: docs

on:
  # 每当 push 到 git-pages 分支时触发部署
  push:
    branches: [git-pages]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: '14'

      # 缓存 node_modules
      - name: Cache Dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # 如果缓存没有命中，安装依赖
      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      # 运行构建脚本
      - name: Build Git Pages
        run: yarn build

      # 部署到 Github Pages
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: git-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 同步到 Gitee
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        with:
          source-repo: git@github.com:MillCloud/developer-examination.git
          destination-repo: git@gitee.com:MillCloud/developer-examination.git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}

      # 部署到 Gitee Pages
      # - name: Deploy to Gitee Pages
      #   uses: yanglbme/gitee-pages-action@main
      #   with:
      #     gitee-username: ModyQyW
      #     gitee-password: ${{ secrets.GITEE_PASSWORD }}
      #     gitee-repo: MillCloud/developer-examination
      #     branch: git-pages
